import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css"
import { Toaster } from "sonner";
import { manrope,figtree,inter } from "./lib/fonts";
import AuthGuard from "./(auth)/AuthGuard";







export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${manrope.variable} ${figtree.variable} ${inter.variable} h-full antialiased`}
    >
    <body className={`${figtree.className} min-h-full bg-red-500 flex flex-col`}>{children}
    <AuthGuard>
        <Toaster
          position="top-right"
          richColors
          closeButton
        />
        </AuthGuard>
    </body>
      
    </html>
  );
}
