export const GUEST_USER_ID_KEY = "guest-user-id"
export const STRIPE_CUSTOMER_ID_KEY = "stripe-customer-id"
export const GUEST_FULL_NAME_KEY = "guest-full-name"
export const GUEST_EMAIL_KEY = "guest-email"
export const GUEST_CONTACT_KEY = "guest-contact-number"
export const GUEST_PAYMENT_METHOD_KEY = "guest-payment-method"
